name: mube
description: "Mube MVP Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Architecture & State Management
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  go_router: ^17.0.1 # Intermediate update
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  
  # Firebase (Updated for Flutter 3.38+)
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1
  firebase_auth: ^6.1.3
  firebase_messaging: ^16.1.0
  
  # UI & Assets
  google_fonts: ^6.2.1
  flutter_svg: ^2.2.3
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  uuid: ^4.2.2
  geolocator: ^14.0.2
  
  # Utilities
  shared_preferences: ^2.5.4
  mask_text_input_formatter: ^2.9.0
  http: ^1.6.0
  font_awesome_flutter: ^10.12.0
  firebase_storage: ^13.0.5
  image_picker: ^1.2.1
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  image_cropper: ^11.0.0
  flutter_image_compress: ^2.4.0
  video_compress: ^3.1.4
  video_player: ^2.10.1
  flutter_reorderable_grid_view: ^5.5.2
  flutter_native_splash: ^2.4.7
  url_launcher: ^6.3.2

  path: ^1.9.1
  path_provider: ^2.1.5
  meta: ^1.17.0
  diacritic: ^0.1.6
  fpdart: ^1.2.0
  firebase_app_check: ^0.4.1+4
  like_button: ^2.1.0
  flutter_cache_manager: ^3.4.1
  # cloud_functions: ^6.0.6
  timeago: ^3.7.1
  flutter_card_swiper: ^7.2.0
  google_nav_bar: 5.0.7
  faker: ^2.2.0
  easy_refresh: ^3.4.0
  flutter_local_notifications: ^17.2.3
  # bitsdojo_window (Desktop only if needed, removed for mobile MVP)


  widgetbook: any
  widgetbook_annotation: any
  flutter_markdown: ^0.7.7+1
  printing: ^5.14.2
  share_plus: ^12.0.1
  pdf: ^3.11.3
  firebase_analytics: ^12.1.1
  firebase_crashlytics: ^5.0.7
  firebase_remote_config: ^6.1.4
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  
  # Testing
  mockito: ^5.4.5
  
  # Generators
  build_runner: ^2.10.5
  riverpod_generator: ^3.0.3
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  
  # Lints
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  window_manager: ^0.5.1
  widgetbook_generator: ^3.20.1
  fake_cloud_firestore: ^4.0.1



  cloud_firestore_platform_interface: any
flutter:
  uses-material-design: true
  generate: true  # Enable localization code generation
  
  assets:
    - assets/images/
    - assets/images/logos_png/
    - assets/images/logos_svg/
    - assets/images/icons/
    - assets/images/app_icon/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon/playstore.png"
  adaptive_icon_background: "#0E0E0E" # AppColors.background
  adaptive_icon_foreground: "assets/images/app_icon/playstore.png"

flutter_native_splash:
  color: "#0E0E0E"
  image: "assets/images/logos_png/logo vertical.png"
  android_12:
    image: "assets/images/app_icon/playstore.png"
    icon_background_color: "#0E0E0E"
  # Adicionado para evitar que a logo fique gigante em telas grandes
  ios_content_mode: scaleAspectFit
  android_gravity: center
  fullscreen: false
