name: mube
description: "Mube MVP Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Architecture & State Management
  flutter_riverpod: ^3.0.3 # Keeping 2.x for stability with current code
  riverpod_annotation: ^3.0.3
  go_router: ^17.0.1 # Intermediate update
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  
  # Firebase (Updated for Flutter 3.38+)
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1
  firebase_auth: ^6.1.3
  firebase_messaging: ^16.1.0
  
  # UI & Assets
  google_fonts: ^6.2.1
  flutter_svg: ^2.2.3
  intl: ^0.20.2
  uuid: ^4.2.2
  geolocator: ^14.0.2
  
  # Utilities
  shared_preferences: ^2.2.2
  mask_text_input_formatter: ^2.9.0
  http: ^1.6.0
  font_awesome_flutter: ^10.12.0
  firebase_storage: ^13.0.5
  image_picker: ^1.2.1
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  image_cropper: ^11.0.0
  flutter_image_compress: ^2.4.0
  video_compress: ^3.1.4
  video_player: ^2.10.1
  dotted_border: ^3.1.0
  flutter_reorderable_grid_view: ^5.5.2
  flutter_native_splash: ^2.4.7
  url_launcher: ^6.3.2
  faker: ^2.2.0
  firebase_database: ^12.1.1
  # bitsdojo_window (Desktop only if needed, removed for mobile MVP)

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  
  # Testing
  mockito: ^5.4.5
  
  # Generators
  build_runner: ^2.4.8
  riverpod_generator: ^3.0.3
  freezed: ^3.2.3
  json_serializable: ^6.7.1
  
  # Lints
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  image: ^4.7.2
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/logos_png/
    - assets/images/logos_svg/
    - assets/images/icons/
    - assets/images/app_icon/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon/playstore.png"
  adaptive_icon_background: "#0E0E0E" # AppColors.background
  adaptive_icon_foreground: "assets/images/app_icon/playstore.png"

flutter_native_splash:
  color: "#0E0E0E"
  image: "assets/images/logos_png/logo vertical.png"
  android_12:
    image: "assets/images/app_icon/playstore.png"
    icon_background_color: "#0E0E0E"
  # Adicionado para evitar que a logo fique gigante em telas grandes
  ios_content_mode: center
  android_gravity: center
  fullscreen: false
